spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_course_manager
    username: your_username_here
    password: your_password_here
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080
